### ISSUE TITLE
is this possible to modeling multi turn dialog.......here is new dataset

### ISSUE THREAD

**Issue by SeekPoint** [chaitjo/personalized-dialog#4]
https://nlp.stanford.edu/blog/a-new-multi-turn-multi-domain-task-oriented-dialogue-dataset/

**Comment by loveJasmine** [comment]
https://nlp.stanford.edu/blog/a-new-multi-turn-multi-domain-task-oriented-dialogue-dataset/

**Comment by chaitjo** [comment]
Hey @loveJasmine , if your intention is to use the Memory Network model for this dataset, I don't see why it should not be possible. although I am not sure this would be the best model for this task in terms of performance. You may have to make the model generate an output instead of discriminate one depending on how they have framed their evaluation.
