### ISSUE TITLE
Why do you choose these datasets and baselines?

### ISSUE THREAD

**Issue by cstghitpku** [chaitjo/personalized-dialog#7]
Incorporating personalization into Task-oriented dialogue systems is almost a largely unexplored topic as there are no existing corpora to facilitate such work. 
Why do you choose these datasets and these baselines? Is there some more recognized  and convincing datasets and baselines？
Your smart and useful work help me a lot.Thank you and I'm looking forward to your reply.

**Comment by chaitjo** [comment]
Hi @cstghitpku, thanks for the interest! I'm happy this could help you out.

Since this paper came out at NIPS '17, there has been some further work on dialog systems + personalization that I can refer you to:
1. FAIR's PersonaChat for the chit-chat setting: https://arxiv.org/pdf/1801.07243.pdf (There are several papers which follow up on this, and NIPS '18 is having a challenge for this dataset.)
2. Use transfer learning on some real world data (roughly goal-oriented): https://arxiv.org/pdf/1610.02891.pdf
3. Evaluate several types of models on chit-chat movie dialogs: https://www.ijcai.org/proceedings/2017/0521.pdf
4. Personalization using profile/personality embeddings: https://www.ijcai.org/proceedings/2018/0595.pdf (You can look at more work by this group at Tsinghua for similar ideas.)

I hope that gives you better data to work with, or some new models to try out. :)

**Comment by cstghitpku** [comment]
Thank you very much, and I have read all these papers before. Although these works are excellent, in term of personalization, there is a big gap between the chit-chat dialogue systems and task-oriented dialogue systems. If you're a reviewer, are there some more recognized and convincing datasets and baselines only for task-oriented dialogue systems？Thank you.

**Comment by chaitjo** [comment]
I haven't encountered, for example, real-world dialog corpuses which have well-defined goals like the bAbI dialog tasks except this one by Stanford: https://nlp.stanford.edu/blog/a-new-multi-turn-multi-domain-task-oriented-dialogue-dataset/

(I'm not very familiar with this dataset, personally.)

**Comment by cstghitpku** [comment]
Thank you. We can only modify recognized and convincing datasets of task-oriented dialogue systems (as your paper do) or use simulator datasets(actually very different from human conversation).Also, so far, do you know some open source codes as better baselines of personalization for task-oriented dialogue systems?

**Comment by chaitjo** [comment]
This papers has been accepted to AAAI '19: https://arxiv.org/pdf/1811.04604.pdf
